### ISSUE TITLE
[iOS][Android] RNCNetInfo.getCurrentState was called with X arguments but expected X arguments.

### ISSUE THREAD

**Issue by alimek** [rgommezz/react-native-offline#240]
### Current Behavior

After update `@react-native-community/netinfo` to latest version `5.2.0` getting error when using `ReduxNetworkProvider` component.

[iOS Image](https://ibb.co/ZT8vBfG)

Removing component making error disappearing. Not sure if this is `react-native-offline` problem itself or `@react-native-community/netinfo` yet.

At the moment had to downgrade to `5.1.0` to make it still working.

### Expected Behavior

`ReduxNetworkProvider` and all others functionalities working with latest `@react-native-community/netinfo`  version. 

### How to reproduce

```
const CustomProvider = () => (
  <Provider store={store}>
    <PersistGate persistor={persistor}>
      <ReduxNetworkProvider>
        <App />
      </ReduxNetworkProvider>
    </PersistGate>
  </Provider>
);
```

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline |  5.2.0
| react-native         | 0.61.5
| node                 | 10.13.0
| npm or yarn          | 1.17.3

**Comment by FadiAboMsalam** [comment]
same issue here @alimek  did you manage to fix it?

**Comment by kiyoshinyobee** [comment]
i have same problem when using `@react-native-community/netinfo` version 5 above.
temporary solved issue is downgrade `@react-native-community/netinfo` to version < 5.0

i'm using `react-native-offline` v5.2.0

**Comment by magickasoft** [comment]
@matinzd provided a solution - when can we expect a package update?
https://github.com/rgommezz/react-native-offline/pull/241 PR

**Comment by nikhilgoswami** [comment]
> @matinzd provided a solution - when can we expect a package update?
> #241 PR

I have made same changes as mentioned in @matinzd PR but I still get similar error for [#282 ](https://github.com/react-native-community/react-native-netinfo/issues/282) **(only I get 2 arguments expected 3)** they tell that it is a environment configuration related issue. Now I am using Ubuntu and android when I import only NetInfo from @react-native-community/netinfo I get no error this error occurs when I import from react-native-offline package.

**Comment by rgommezz** [comment]
Hey guys, version v5.4.0 should solve the issue

**Comment by sudomann** [comment]
I'm still getting this error even though I'm on version 5.4.0

**Comment by alimek** [comment]
@sudomann did you updated netinfo lib? i installed today latest version of both lib and it is working fine for me.

**Comment by sudomann** [comment]
@alimek When rolling back to react-native-offline@5.4.0 didn't work I reinstalled the latest. 5.5.0. I have been making sure not to mess with the dependency versions

**Comment by sudomann** [comment]
@alimek Good suggestion, manually installing the latest version of netinfo (5.5.0) fixed it.

**Comment by dellwatson** [comment]
@alimek @sudomann this problem still occurs in netinfo v5.5.0, r-n-offline v5.4.0,  i use example to testing
