### ISSUE TITLE
[Typescript Error] ReduxNetworkProvider gives error for property children

### ISSUE THREAD

**Issue by cnkyrpsgl** [rgommezz/react-native-offline#269]
### Current Behavior

- Related code => 

`

    <Provider store={store}>
        <ReduxNetworkProvider
          pingServerUrl={`${REST_URL}/health`}
          pingInBackground={true}
          pingTimeout={3000}
          pingInterval={5000}
      >
        <PersistGate loading={null} persistor={persistor}>
          <PaperProvider>
            <App />
          </PaperProvider>
        </PersistGate>
      </ReduxNetworkProvider>
    </Provider>
  `

- Just compiling typescript and getting this error => 

`Error:(25, 10) TS2322: Type '{ children: Element; pingServerUrl: string; pingInBackground: true; pingTimeout: number; pingInterval: number; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<Props, "pingTimeout" | "pingServerUrl" | "shouldPing" | "pingInterval" | "pingOnlyIfOffline" | "pingInBackground" | "httpMethod">, never> & Partial<...> & Partial<...>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<Pick<Props, "pingTimeout" | "pingServerUrl" | "shouldPing" | "pingInterval" | "pingOnlyIfOffline" | "pingInBackground" | "httpMethod">, never> & Partial<...> & Partial<...>'.`

### Expected Behavior

- Not giving any compilation error

### How to reproduce

- Just open the file

### Your Environment

| software             | version
| ----------------     | -------
| react-native-offline | 5.6.1
| react-native         | 0.61.5
| node                 | 13.12.0
| npm or yarn          | npm

**Comment by jayjac** [comment]
What's weird is if you remove the props, the warning seems to disappear. Did you get it fixed ?

**Comment by npwork** [comment]
Same here on "react-native-offline": "^5.6.1",

**Comment by npwork** [comment]
As a temporary workaround:
`
{/*
// @ts-ignore */}
`

**Comment by rgommezz** [comment]
Thanks for the report! Version `5.6.2` should fix it.

**Comment by skizzo** [comment]
This is still an issue for me for version `6.0.2`. Anybody else?
